# Generated by Django 5.2.4 on 2025-07-30 22:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('biography', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='music_catal_name_c2438a_idx'), models.Index(fields=['country', 'is_active'], name='music_catal_country_c4eb88_idx')],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('total_tracks', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music_catalog.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music_catalog.genre')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7200)])),
                ('file_url', models.URLField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('track_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('play_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_catalog.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music_catalog.genre')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['album', 'track_number', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'release_date'], name='music_catal_artist__c1990b_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['genre', 'is_active'], name='music_catal_genre_i_27dd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['title', 'is_active'], name='music_catal_title_6c50e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'artist')},
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist', 'is_active'], name='music_catal_artist__f7e14c_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['album', 'track_number'], name='music_catal_album_i_56de87_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre', 'is_active'], name='music_catal_genre_i_acc2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title', 'is_active'], name='music_catal_title_31b935_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-play_count', 'is_active'], name='music_catal_play_co_cec7d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'track_number'), ('title', 'artist', 'album')},
        ),
    ]
