# Generated by Django 5.2.4 on 2025-08-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlbumModel",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Título del álbum"),
                ),
                ("artist_id", models.UUIDField(verbose_name="ID del artista")),
                (
                    "artist_name",
                    models.CharField(
                        help_text="Desnormalizado para rendimiento",
                        max_length=200,
                        verbose_name="Nombre del artista",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de lanzamiento"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de portada"
                    ),
                ),
                (
                    "total_tracks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de pistas"
                    ),
                ),
                (
                    "play_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Reproducciones"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Álbum",
                "verbose_name_plural": "Álbumes",
                "db_table": "albums",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="albums_title_063196_idx"),
                    models.Index(
                        fields=["artist_id"], name="albums_artist__2d0263_idx"
                    ),
                    models.Index(
                        fields=["release_date"], name="albums_release_27939f_idx"
                    ),
                    models.Index(
                        fields=["play_count"], name="albums_play_co_ef71d3_idx"
                    ),
                ],
            },
        ),
    ]
