# Generated by Django 5.2.4 on 2025-08-03 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="albummodel",
            name="is_active",
        ),
    ]
