# Generated by Django 5.2.4 on 2025-08-04 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0002_add_source_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="albummodel",
            name="unique_album_source_per_type",
        ),
        migrations.RemoveIndex(
            model_name="albummodel",
            name="albums_albummodel_source_type_source_id_idx",
        ),
        migrations.RemoveField(
            model_name="albummodel",
            name="source_id",
        ),
        migrations.RemoveField(
            model_name="albummodel",
            name="source_type",
        ),
        migrations.RemoveField(
            model_name="albummodel",
            name="source_url",
        ),
    ]
