# Generated by Django 5.2.4 on 2025-08-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0004_albummodel_source_id_albummodel_source_type_and_more"),
        (
            "artists",
            "0003_rename_artists_artistmodel_source_type_source_id_idx_artists_source__a58f1f_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="albummodel",
            name="albums_artist__2d0263_idx",
        ),
        migrations.RemoveField(
            model_name="albummodel",
            name="artist_id",
        ),
        migrations.RemoveField(
            model_name="albummodel",
            name="artist_name",
        ),
        migrations.AddField(
            model_name="albummodel",
            name="artist",
            field=models.ForeignKey(
                default="123e4567-e89b-12d3-a456-426614174000",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="artists.artistmodel",
                verbose_name="Artista",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="albummodel",
            index=models.Index(fields=["artist"], name="albums_artist__2d0263_idx"),
        ),
    ]
