# Generated by Django 5.2.4 on 2025-08-08 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_albummodel_albums_artist__2d0263_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
