# Generated by Django 5.2.4 on 2025-08-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtistModel",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del artista"),
                ),
                (
                    "biography",
                    models.TextField(blank=True, null=True, verbose_name="Biografía"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="País"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de imagen"
                    ),
                ),
                (
                    "followers_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad de seguidores"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Artista",
                "verbose_name_plural": "Artistas",
                "db_table": "artists",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="artists_name_b2ca99_idx"),
                    models.Index(fields=["country"], name="artists_country_758c4f_idx"),
                    models.Index(
                        fields=["is_verified"], name="artists_is_veri_9de97b_idx"
                    ),
                    models.Index(
                        fields=["followers_count"], name="artists_followe_6298fc_idx"
                    ),
                ],
            },
        ),
    ]
