# Generated by Django 5.2.4 on 2025-08-04 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0002_add_source_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="artistmodel",
            new_name="artists_source__a58f1f_idx",
            old_name="artists_artistmodel_source_type_source_id_idx",
        ),
        migrations.RemoveField(
            model_name="artistmodel",
            name="is_active",
        ),
    ]
