# Generated by Django 5.2.4 on 2025-08-05 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "artists",
            "0003_rename_artists_artistmodel_source_type_source_id_idx_artists_source__a58f1f_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artistmodel",
            name="unique_artist_source_per_type",
        ),
        migrations.RemoveIndex(
            model_name="artistmodel",
            name="artists_country_758c4f_idx",
        ),
        migrations.RemoveIndex(
            model_name="artistmodel",
            name="artists_source__a58f1f_idx",
        ),
        migrations.RemoveField(
            model_name="artistmodel",
            name="country",
        ),
        migrations.RemoveField(
            model_name="artistmodel",
            name="source_id",
        ),
        migrations.RemoveField(
            model_name="artistmodel",
            name="source_type",
        ),
        migrations.RemoveField(
            model_name="artistmodel",
            name="source_url",
        ),
    ]
