# Generated by Django 5.2.4 on 2025-08-08 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_remove_artistmodel_unique_artist_source_per_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
