# Generated by Django 5.2.4 on 2025-08-04 19:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("songs", "0005_remove_songmodel_songs_album_t_6c7985_idx_and_more"),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si es una playlist por defecto (como 'Favoritos') que no se puede eliminar",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la playlist es pública o privada",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario propietario de la playlist",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to="user_profile.userprofilemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "db_table": "playlists",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistSongModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Posición de la canción en la playlist (empezando desde 1)"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        help_text="Playlist que contiene la canción",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="playlists.playlistmodel",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        help_text="Canción en la playlist",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_entries",
                        to="songs.songmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canción en Playlist",
                "verbose_name_plural": "Canciones en Playlists",
                "db_table": "playlist_songs",
                "ordering": ["playlist", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="playlistmodel",
            index=models.Index(
                fields=["user", "is_default"], name="playlists_user_id_d5c0c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistmodel",
            index=models.Index(
                fields=["user", "created_at"], name="playlists_user_id_645197_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user", "name"),
                name="unique_default_playlist_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="playlistsongmodel",
            index=models.Index(
                fields=["playlist", "position"], name="playlist_so_playlis_c53573_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistsongmodel",
            index=models.Index(fields=["song"], name="playlist_so_song_id_5b2cc9_idx"),
        ),
        migrations.AddConstraint(
            model_name="playlistsongmodel",
            constraint=models.UniqueConstraint(
                fields=("playlist", "song"), name="unique_song_per_playlist"
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistsongmodel",
            constraint=models.UniqueConstraint(
                fields=("playlist", "position"), name="unique_position_per_playlist"
            ),
        ),
    ]
