# Generated by Django 5.2.4 on 2025-08-05 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0001_initial"),
        ("songs", "0005_remove_songmodel_songs_album_t_6c7985_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistmodel",
            name="song_list",
            field=models.ManyToManyField(
                help_text="Canciones que contiene esta playlist",
                related_name="playlists_containing",
                through="playlists.PlaylistSongModel",
                to="songs.songmodel",
            ),
        ),
        migrations.AlterField(
            model_name="playlistsongmodel",
            name="playlist",
            field=models.ForeignKey(
                help_text="Playlist que contiene la canción",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_songs",
                to="playlists.playlistmodel",
            ),
        ),
    ]
