# Generated by Django 5.2.4 on 2025-08-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0002_playlistmodel_song_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistmodel",
            name="playlist_img",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
