# Generated by Django 5.2.4 on 2025-07-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artista",
            fields=[
                ("artista_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_artista", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=50)),
                ("url_imagen_artista", models.CharField(max_length=200)),
                ("url_imagen", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Cancion",
            fields=[
                ("cancion_id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo_cancion", models.CharField(max_length=200)),
                ("duracion", models.IntegerField(help_text="Duración en segundos")),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                ("genero_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_genero", models.CharField(max_length=50)),
                ("descripcion_genero", models.CharField(max_length=500)),
                ("imagen_url_genero", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("usuario_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("fecha_registro", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticaArtista",
            fields=[
                (
                    "artista",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="music.artista",
                    ),
                ),
                ("total_reproducciones", models.IntegerField()),
                ("minutos_escuchados", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                ("album_id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo_album", models.CharField(max_length=200)),
                ("fecha_lanzamiento", models.DateField()),
                ("url_imagen_album", models.CharField(max_length=200)),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artista"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticaCancion",
            fields=[
                (
                    "cancion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="music.cancion",
                    ),
                ),
                ("total_reproducciones", models.IntegerField()),
                ("minutos_escuchados", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="cancion",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="music.album"
            ),
        ),
        migrations.CreateModel(
            name="EstadisticaGenero",
            fields=[
                (
                    "genero",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="music.genero",
                    ),
                ),
                ("total_reproducciones", models.IntegerField()),
                ("minutos_escuchados", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="cancion",
            name="genero",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music.genero",
            ),
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                ("suscripcion_id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_plan", models.CharField(max_length=50)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="music.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("playlist_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_playlist", models.CharField(max_length=100)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("canciones", models.ManyToManyField(to="music.cancion")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                ("perfil_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_perfil", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=100)),
                ("avatar_url", models.CharField(max_length=200)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="music.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticaUsuario",
            fields=[
                (
                    "estadisticas_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("total_reproducciones", models.IntegerField()),
                ("minutos_escuchados", models.IntegerField()),
                ("fecha_ultima_actualizacion", models.DateField()),
                (
                    "artista_favorito",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.artista",
                    ),
                ),
                (
                    "cancion_favorita",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favorita_usuario",
                        to="music.cancion",
                    ),
                ),
                (
                    "genero_favorito",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.genero",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="music.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticaCancionUsuario",
            fields=[
                (
                    "estadistica_cancion_usuario_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("veces_reproducidas", models.IntegerField()),
                ("minutos_escuchados", models.IntegerField()),
                (
                    "cancion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.cancion"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.usuario"
                    ),
                ),
            ],
        ),
    ]
