# Generated by Django 5.2.4 on 2025-08-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenreModel",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del género"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de imagen"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        help_text="Color en formato hexadecimal (#RRGGBB)",
                        max_length=7,
                        null=True,
                        verbose_name="Color representativo",
                    ),
                ),
                (
                    "popularity_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntuación de popularidad"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Género Musical",
                "verbose_name_plural": "Géneros Musicales",
                "db_table": "genres",
                "ordering": ["-popularity_score", "name"],
            },
        ),
    ]
