# Generated by Django 5.2.4 on 2025-08-04 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="songmodel",
            name="songs_artist__30c12a_idx",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="artist_name",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="genre_names",
        ),
    ]
