# Generated by Django 5.2.4 on 2025-08-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genres", "0002_remove_genremodel_is_active"),
        ("songs", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="songmodel",
            name="songs_genre_n_15f23c_idx",
        ),
        migrations.RemoveIndex(
            model_name="songmodel",
            name="songs_is_acti_683258_idx",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="genre_id",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="genre_name",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="is_explicit",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="is_premium",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="tags",
        ),
        migrations.AddField(
            model_name="songmodel",
            name="genre_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de nombres de géneros para búsquedas rápidas",
            ),
        ),
        migrations.AddField(
            model_name="songmodel",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                help_text="Géneros musicales asociados a esta canción",
                related_name="songs",
                to="genres.genremodel",
            ),
        ),
    ]
