# Generated by Django 5.2.4 on 2025-08-04 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_add_artist_name_field"),
        ("songs", "0002_remove_songmodel_songs_artist__30c12a_idx_and_more"),
    ]

    operations = []
