# Generated by Django 5.2.4 on 2025-08-04 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0003_merge_20250803_2124"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="songmodel",
            name="songs_artist_name_idx",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="artist_name",
        ),
    ]
