# Generated by Django 5.2.4 on 2025-08-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0005_remove_albummodel_albums_artist__2d0263_idx_and_more"),
        (
            "artists",
            "0003_rename_artists_artistmodel_source_type_source_id_idx_artists_source__a58f1f_idx_and_more",
        ),
        ("songs", "0004_remove_songmodel_songs_artist_name_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="songmodel",
            name="songs_album_t_6c7985_idx",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="album_id",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="album_title",
        ),
        migrations.RemoveField(
            model_name="songmodel",
            name="artist_id",
        ),
        migrations.AddField(
            model_name="songmodel",
            name="album",
            field=models.ForeignKey(
                blank=True,
                help_text="Álbum de la canción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs",
                to="albums.albummodel",
            ),
        ),
        migrations.AddField(
            model_name="songmodel",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                help_text="Artista de la canción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs",
                to="artists.artistmodel",
            ),
        ),
    ]
