from .utils.env import env

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = env(
    "STRIPE_PUBLISHABLE_KEY",
)
STRIPE_SECRET_KEY = env(
    "STRIPE_SECRET_KEY",
)
STRIPE_WEBHOOK_SECRET = env(
    "STRIPE_WEBHOOK_SECRET",
)

# Stripe Product Price IDs
STRIPE_PREMIUM_MONTHLY_PRICE_ID = env(
    "STRIPE_PREMIUM_MONTHLY_PRICE_ID",
)
STRIPE_PREMIUM_YEARLY_PRICE_ID = env(
    "STRIPE_PREMIUM_YEARLY_PRICE_ID",
)
