from .utils.env import env

SUPABASE_PROJECT_ID = env("SUPABASE_PROJECT_ID")
SUPABASE_URL = env("SUPABASE_URL")
SUPABASE_ANON_KEY = env("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_KEY = env("SUPABASE_SERVICE_KEY")
SUPABASE_JWT_SECRET = env("SUPABASE_JWT_SECRET")

TOKEN_EXPIRATION_TIME = env(
    "TOKEN_EXPIRATION_TIME",
    cast=int,
)
SUPABASE_JWT_ALGORITHM = env.list("SUPABASE_JWT_ALGORITHM")
