# Generated by Django 5.2.4 on 2025-08-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "email",
                    models.EmailField(editable=False, max_length=254, unique=True),
                ),
                (
                    "profile_picture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
