# Generated by Django 5.2.4 on 2025-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_profile",
            "0002_userprofile_profile_picture_alter_userprofile_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
