# Generated by Django 5.2.4 on 2025-07-31 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_profile",
            "0002_userprofile_profile_picture_alter_userprofile_email_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="UserProfileModel",
        ),
    ]
