# Generated by Django 5.2.4 on 2024-12-04

from django.db import migrations, models
import hashlib


def populate_passwords(apps, schema_editor):
    """Populate empty passwords with a default hashed value"""
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    default_password = "temp_password_123"
    hashed_password = hashlib.sha256(default_password.encode()).hexdigest()
    
    # Update all users without passwords
    UserProfile.objects.filter(password__isnull=True).update(password=hashed_password)
    UserProfile.objects.filter(password="").update(password=hashed_password)


def reverse_populate_passwords(apps, schema_editor):
    """Reverse operation - set passwords to null"""
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    UserProfile.objects.all().update(password=None)


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_password'),
    ]

    operations = [
        # First, make the field optional and populate it
        migrations.RunPython(populate_passwords, reverse_populate_passwords),
        
        # Then make the field required
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='Contraseña del usuario (hasheada)', max_length=255),
        ),
    ]
