# Generated by Django 5.2.4 on 2025-08-01 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_rename_userprofile_userprofilemodel"),
        ("user_profile", "0004_populate_and_require_password"),
    ]

    operations = []
