# Generated by Django 5.2.4 on 2025-08-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0005_merge_20250801_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilemodel",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
