# Generated by Django 5.2.4 on 2025-08-02 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_alter_userprofilemodel_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofilemodel",
            name="password",
        ),
    ]
